Fix compilation error of ULTs on Windows
The build of test_cmdlist_append_launch_kernel_1.cpp caused
fatal error C1128 - number of sections exceeded object file
format limit.

Signed-off-by: Patryk Wrobel <patryk.wrobel@intel.com>